server:
  port: 9094

spring:
  application:
    name: AUTHORIZATION-SERVICE
# eureka:
#   client:
#     register-with-eureka: true
#     fetch-registry: true
#     service-url:
#       defaultZone: http://EUREKA-SERVER:8761/eureka       