version: '3'
services:
  EUREKA-SERVER:
    container_name: eureka-server
    #build: Backend/ReturnOrderManagementSystem-EurekaServer
    image: public.ecr.aws/y8y1h0j5/aravraja/eurekaserver
    
    ports:
      - "8761:8761"
  API-GATEWAY:
    container_name: apigateway
    #build: Backend/ReturnOrderManagementSystem-APIGetWay
    image: public.ecr.aws/y8y1h0j5/aravraja/apigateway
    
    ports:
      - "80:9191" 
    environment:
       SPRING_CLOUD_CONFIG_URI: http://CONFIG-SERVER:9999
       SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://EUREKA-SERVER:8761/eureka"}}}}'
     
    depends_on:
      - EUREKA-SERVER 
      # - cloudgateway
    # environment:
    #   eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka  
  CONFIG-SERVER:
    container_name: cloud
    #build: Backend/ReturnOrderManagementSystem-CloudConfig
    image: public.ecr.aws/y8y1h0j5/aravraja/cloud
    
    ports:
      - "9999:9999" 
    environment:
       SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://EUREKA-SERVER:8761/eureka"}}}}'
     
    depends_on:
      - EUREKA-SERVER   
      - API-GATEWAY  

  AUTHORIZATION-SERVICE:
    container_name: auth
    #build: Backend/ReturnOrderManagementSystem-Authorizatin
    image: public.ecr.aws/y8y1h0j5/aravraja/auth
    
    ports:
      - "9091:9091" 
    environment:
       SPRING_CLOUD_CONFIG_URI: http://CONFIG-SERVER:9999 
       SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://EUREKA-SERVER:8761/eureka"}}}}'
     
    depends_on:
      - EUREKA-SERVER   
      - API-GATEWAY 
      - CONFIG-SERVER
  COMPONENT-PROCESSING:
    container_name: comp-process
    #build: Backend/ReturnOrderManagementSystem-ComponentProcessing
    image: public.ecr.aws/y8y1h0j5/aravraja/comp-process
    
    ports:
      - "9090:9090" 
    environment:
       SPRING_CLOUD_CONFIG_URI: http://CONFIG-SERVER:9999 
       SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://EUREKA-SERVER:8761/eureka"}}}}'
     
    depends_on:
      - EUREKA-SERVER   
      - API-GATEWAY 
      - CONFIG-SERVER   
  PACKAGING-AND-DELIVERY:
    container_name: packaging-and-delivery
    #build: Backend/ReturnOrderManagementSystem-PackagingAndDelivery
    image: public.ecr.aws/y8y1h0j5/aravraja/packaging-and-delivery
    
    ports:
      - "9092:9092" 
    environment:
       SPRING_CLOUD_CONFIG_URI: http://CONFIG-SERVER:9999 
       SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://EUREKA-SERVER:8761/eureka"}}}}'
     
    depends_on:
      - EUREKA-SERVER   
      - API-GATEWAY 
      - CONFIG-SERVER       
      