version: 0.2
phases:
  build:
    commands:
      - echo "$DOCKER_PW" | docker login -u "$DOCKER_ID" --password-stdin	
      - REPOSITORY_URI=public.ecr.aws/y8y1h0j5/aravraja/packaging-and-delivery:latest
      - docker-compose -f dck.yml  build
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/y8y1h0j5
      - docker tag aravraja/packaging-and-delivery:latest public.ecr.aws/y8y1h0j5/aravraja/packaging-and-delivery:latest
      - docker push public.ecr.aws/y8y1h0j5/aravraja/packaging-and-delivery:latest
      - touch imagedefinitions.json
      - printf '[{"name":"PACK","imageUri":"%s"}]' $REPOSITORY_URI > imagedefinitions.json
      - cat imagedefinitions.json
      
artifacts:
  files: imagedefinitions.json
      