version: '2'
services:
  EUREKA-SERVER:
    container_name: eureka-server
    build: ReturnOrderManagementSystem-EurekaServer
    image: eurekaserver
    
    ports:
      - "8761:8761"
  API-GATEWAY:
    container_name: apigateway
    build: ReturnOrderManagementSystem-APIGetWay
    image: apigateway
    
    ports:
      - "9191:9191" 
    environment:
       SPRING_CLOUD_CONFIG_URI: http://CONFIG-SERVER:9999
       SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://EUREKA-SERVER:8761/eureka"}}}}'
     
    depends_on:
      - EUREKA-SERVER 
      # - cloudgateway
    # environment:
    #   eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka  
  CONFIG-SERVER:
    container_name: cloud
    build: ReturnOrderManagementSystem-CloudConfig
    image: cloud
    
    ports:
      - "9999:9999" 
    environment:
       SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://EUREKA-SERVER:8761/eureka"}}}}'
     
    depends_on:
      - EUREKA-SERVER   
      - API-GATEWAY  

  AUTHORIZATION-SERVICE:
    container_name: auth
    build: ReturnOrderManagementSystem-Authorizatin
    image: auth
    
    ports:
      - "9091:9091" 
    environment:
       SPRING_CLOUD_CONFIG_URI: http://CONFIG-SERVER:9999 
       SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://eureka-server:8761/eureka"}}}}'
     
    depends_on:
      - EUREKA-SERVER   
      - API-GATEWAY 
      - CONFIG-SERVER
  COMPONENT-PROCESSING:
    container_name: comp-process
    build: ReturnOrderManagementSystem-ComponentProcessing
    image: comp-process
    
    ports:
      - "9090:9090" 
    environment:
       SPRING_CLOUD_CONFIG_URI: http://CONFIG-SERVER:9999 
       SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://eureka-server:8761/eureka"}}}}'
     
    depends_on:
      - EUREKA-SERVER   
      - API-GATEWAY 
      - CONFIG-SERVER   
  PACKAGING-AND-DELIVERY:
    container_name: packaging-and-delivery
    build: ReturnOrderManagementSystem-PackagingAndDelivery
    image: packaging-and-delivery
    
    ports:
      - "9092:9092" 
    environment:
       SPRING_CLOUD_CONFIG_URI: http://CONFIG-SERVER:9999 
       SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://eureka-server:8761/eureka"}}}}'
     
    depends_on:
      - EUREKA-SERVER   
      - API-GATEWAY 
      - CONFIG-SERVER       
      