server:
  port: 9090

spring:
  application:
    name: COMPONENT-PROCESSING
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-lb-1611713706.us-east-1.elb.amazonaws.com/eureka       
