server:
  port: 9094

spring:
  application:
    name: AUTHORIZATION-SERVICE
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-lb-1611713706.us-east-1.elb.amazonaws.com/eureka
  instance:
    prefer-ip-address: true          