server:
  port: 9092

spring:
  application:
    name: PACKAGING-AND-DELIVERY

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-lb-1611713706.us-east-1.elb.amazonaws.com/eureka       