server:
  port: 9090

spring:
  application:
    name: COMPONENT-PROCESSING
    
# eureka:
#   client:
#     register-with-eureka: true
#     fetch-registry: true
#     service-url:
#       defaultZone: http://EUREKA-SERVER:8761/eureka       
